// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdy1Ns-02u6RdAHv30KdrIq1wiP19PK5Y',
    appId: '1:874489562461:android:1ea75b78e8b0f32e94d4b4',
    messagingSenderId: '874489562461',
    projectId: 'beliora-bac59',
    storageBucket: 'beliora-bac59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlVZr7UMgzn_oLO2nVw1-PdizMRRTKcQk',
    appId: '1:874489562461:ios:f0425f068696020e94d4b4',
    messagingSenderId: '874489562461',
    projectId: 'beliora-bac59',
    storageBucket: 'beliora-bac59.firebasestorage.app',
    androidClientId: '874489562461-40sp5r5poenqid6g98jtke5r6p9q81vv.apps.googleusercontent.com',
    iosClientId: '874489562461-hsnkpkknh038r86o59pd5q36h9kusvt8.apps.googleusercontent.com',
    iosBundleId: 'com.example.beliora1',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHeWW0dIMAYQ-7wxN0TavdcrEq9WrIBuA',
    appId: '1:874489562461:web:41d970bc36d26e3294d4b4',
    messagingSenderId: '874489562461',
    projectId: 'beliora-bac59',
    authDomain: 'beliora-bac59.firebaseapp.com',
    storageBucket: 'beliora-bac59.firebasestorage.app',
    measurementId: 'G-VVC46FRED4',
  );

}